### ISSUE TITLE
Elementor image-box -> description - adds an extra paragraph tag

### ISSUE THREAD

**Issue by GeorgeBotsev** [OnTheGoSystems/wpml-page-builders-elementor#10]
The Elementor element image-box has two fields - title and description.
The title is set to "Line" type, but the description is set to "Visual" type.
Because it is set to "Visual", when translated, in the translation there is an extra paragraph (<p>) tag and the  element contents are actually outside of the proper tag.
![image](https://user-images.githubusercontent.com/4906133/38087248-159bbcf6-3360-11e8-9cb4-15cf255d1190.png)
If we change the element type to "Line" for the description - there is no issue, but then you miss the fine controls in the translation editor - which is a minus.

**Comment by adrianosferreira** [comment]
@GeorgeBotsev fixed in https://github.com/OnTheGoSystems/wpml-page-builders-elementor/pull/14

**Comment by strategio** [comment]
This has been fixed in https://github.com/OnTheGoSystems/wpml-page-builders-elementor/pull/14, closing the issue.
