### ISSUE TITLE
Elementor Pro - missing Call to Action and Blockquote modules in TE

### ISSUE THREAD

**Issue by amElnagdy** [OnTheGoSystems/wpml-page-builders-elementor#13]
It seems that these elements are not registered for translation:
**Call to Action** and **Blockquote** 

**Steps:**
- Install Elementor and Elementor PRO
- Create a new page and add **Call to Action** and **Blockquote**  elements.
- Translate using Translation Editor.

![cta](https://user-images.githubusercontent.com/7650147/40653063-4c9fcf62-633a-11e8-9490-11a90f5610de.png)
![block](https://user-images.githubusercontent.com/7650147/40653064-4cc65cea-633a-11e8-9ab5-2dec90ff1c80.png)

**Comment by adrianosferreira** [comment]
@amElnagdy fixed in https://github.com/OnTheGoSystems/wpml-page-builders-elementor/pull/14

**Comment by amElnagdy** [comment]
Thanks a lot @adrianosferreira. This will be implemented in wpml 4.1, right?

**Comment by adrianosferreira** [comment]
@amElnagdy probably 4.0.0 ;)

**Comment by amElnagdy** [comment]
Awesome. Thanks @adrianosferreira
