### ISSUE TITLE
Elementor Pro - missing modules when using Translation Editor

### ISSUE THREAD

**Issue by GeorgeBotsev** [OnTheGoSystems/wpml-page-builders-elementor#2]
In the translation editor there seems to be missing the ability to translate:
-Animated modules - You can add a highlighted animation to a text. You can translate this manually via Elementor editor in the second language
![image](https://user-images.githubusercontent.com/4906133/36313368-f9def0dc-1339-11e8-8211-b34ec6deb93a.png)

-Post listing widget words for "Read more" - Can be translated as well via Elementor editor in the second language.
![image](https://user-images.githubusercontent.com/4906133/36313536-78e7c1ce-133a-11e8-8d66-aa3fd3693056.png)

-Global modules for Elementor - they can be set as local and unlinked from the global module and this allows you to translate them.

**Comment by adrianosferreira** [comment]
PR https://github.com/OnTheGoSystems/wpml-page-builders-elementor/pull/5
