### ISSUE TITLE
[Feature/ Improvement] Add the ability to translate the Elementor "Icon Box" Link

### ISSUE THREAD

**Issue by GeorgeBotsev** [OnTheGoSystems/wpml-page-builders-elementor#3]
When adding the Elementor Icon Box element (icon-box), you can specify a link.
That link is then not available for translation and it is copied to the translation.
As you can see in https://github.com/OnTheGoSystems/wpml-page-builders-elementor/blob/master/src/class-wpml-elementor-translatable-nodes.php#L339 we have only two elements there and the link element is not one of them.

**Comment by andreasciamanna** [comment]
@adrianosferreira I think we already do something like that (allowing translating a link's URL) for other components or other page builders.

Do you want to give it a look?

**Comment by adrianosferreira** [comment]
@andreasciamanna indeed we do. Sure.

**Comment by adrianosferreira** [comment]
PR https://github.com/OnTheGoSystems/wpml-page-builders-elementor/pull/4
