### ISSUE TITLE
Multiple URL fields not working

### ISSUE THREAD

**Issue by synio-wesley** [OnTheGoSystems/wpml-page-builders-elementor#64]
Related to: https://github.com/pojome/elementor/issues/6786

We found out an issue where multiple URL fields cannot be translated.

Example code that is not working:

```
add_filter('wpml_elementor_widgets_to_translate', function($widgets) {
    $widgets['example_name] = [
        'conditions' => ['widgetType' => 'example_name'],
        'fields' => [
            'url_field_1' => [
                'field' => 'url',
                'type' => __('Example URL Field 1', 'trailactive'),
                'editor_type' => 'LINE', // or 'LINK' but relative links not possible that way
            ],
            'url_field_2' => [
                'field' => 'url',
                'type' => __('Example URL Field 2', 'trailactive'),
                'editor_type' => 'LINE', // or 'LINK' but relative links not possible that way
            ],
        ],
    ];
    return $widgets;
});
```

I have found the issue to be inside of the `class-wpml-elementor-translatable-nodes.php`file.

To fix the issue, we can set `$field['field']` to something like `"{$key}_{$field_key}"` before calling the `get_string_name()` function in `get()` and `update()` (only when `!is_numeric($key)`). I have tested this change and it seems to work fine now!

**I can create a Pull Request if that would be helpful?**

**Comment by adrianosferreira** [comment]
@synio-wesley yes, of course, we really appreciate that. Please create that and we will take a look.

**Comment by strategio** [comment]
This has issue has been fixed by https://github.com/OnTheGoSystems/wpml-page-builders-elementor/pull/67.
