### ISSUE TITLE
[New feature]  Add "field html" in class-wpml-elementor-form.php

### ISSUE THREAD

**Issue by phdenis63** [OnTheGoSystems/wpml-page-builders-elementor#7]
Hello,

Could you add "field-html" in class-wpml-elementor-form.php to enable the possibility to translate html form fields.

Best Regards.
<hr />

public function get_fields() {
return array( 'field_label', 'placeholder', 'field_options'<span style="color: #ff0000;">**_, 'field_html'_**</span> );
}

<hr />

protected function get_title( $field ) {
switch( $field ) {
.....
<span style="color: #ff0000;">**_case 'field_html':_**</span>
<span style="color: #ff0000;"> **_return esc_html__( 'Form: Field html', 'wpml-string-translation' );_**</span>

<hr />

protected function get_editor_type( $field ) {
switch( $field ) {
.....
<span style="color: #ff0000;">**_case 'field_html':_**</span>
<span style="color: #ff0000;"> **_return 'VISUAL';_**</span>

**Comment by adrianosferreira** [comment]
@phdenis63 would you mind sending a PR for this fix feature request?

**Comment by phdenis63** [comment]
@adrianosferreira 

Ok. Done.

I hope I did it correctly. I did not find how to create a branch without creating a fork.

(It is the first time I create a Pull Request on Github)

Best Regards

Philippe

**Comment by adrianosferreira** [comment]
@phdenis63 thanks a lot! I've fixed the unit test and some strings: https://github.com/OnTheGoSystems/wpml-page-builders-elementor/commit/1d77fbbfcfc01a1ddd10fef74eb63b3e753c3c66
